wix-incubator/quix

quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/TestQueryExecutor.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/db/RefreshableDb.scala, quix-backend/quix-modules/quix-presto-module/src/test/scala/quix/presto/db/RefreshableDbTest.scala, quix-backend/quix-webapps/quix-web-spring/pom.xml, quix-backend/quix-webapps/quix-web-spring/src/main/scala/quix/web/spring/SpringConfig.scala, quix-backend/quix-webapps/quix-web-spring/src/test/resources/test.properties, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/E2EContext.scala, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/SpringConfigWithTestExecutor.scala, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/controllers/DbControllerTest.scala, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/controllers/PrestoControllerTest.scala
should fix https://github.com/wix-incubator/quix/issues/26
=> cover quix-backend with E2E tests (issues/26)

quix-backend/quix-api/src/main/scala/quix/api/execute/Api.scala, quix-backend/quix-api/src/main/scala/quix/api/execute/ExecutionProtocol.scala, quix-backend/quix-core/src/main/scala/quix/core/utils/JsonOps.scala, quix-backend/quix-webapps/quix-web-spring/src/main/scala/quix/web/controllers/PrestoController.scala, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/E2EContext.scala, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/controllers/PrestoControllerTest.scala, quix-frontend/client/src/lib/runner/directives/runner/runner.ts, quix-frontend/client/src/lib/runner/directives/sql-runner/sql-runner.ts, quix-frontend/client/src/lib/runner/services/runner-service.ts
=> unify execution events

quix-frontend/service/src/entities/filenode.repository.ts, quix-frontend/service/src/modules/event-sourcing/plugins/file-tree-plugin.ts, quix-frontend/service/src/modules/event-sourcing/plugins/notebook-plugin.ts, quix-frontend/service/src/modules/event-sourcing/quix-event-bus.driver.ts, quix-frontend/service/src/modules/event-sourcing/quix-event-bus.spec.ts, quix-frontend/service/src/modules/web-api/web-api.spec.ts, quix-frontend/service/tslint.json
https://github.com/wix-incubator/quix/issues/47
=> [frontend-service] file tree improvements 

quix-backend/quix-api/src/main/scala/quix/api/execute/ExecutionEngine.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/QueryExecutor.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/TestQueryExecutor.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/rest/PrestoRestApi.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/rest/ScalaJPrestoOps.scala, quix-backend/quix-modules/quix-presto-module/src/test/scala/quix/presto/QueryExecutorTest.scala, quix-backend/quix-modules/quix-presto-module/src/test/scala/quix/presto/rest/ScalaJPrestoOpsTest.scala
=> backend : support use command

quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/PrestoExecutions.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/PrestoQuixModule.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/QueryExecutor.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/TestQueryExecutor.scala, quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/rest/PrestoRestApi.scala, quix-backend/quix-modules/quix-presto-module/src/test/scala/quix/presto/PlainPrestoSqlSupportTest.scala, quix-backend/quix-modules/quix-presto-module/src/test/scala/quix/presto/PrestoExecutionsTest.scala, quix-backend/quix-modules/quix-presto-module/src/test/scala/quix/presto/QueryExecutorTest.scala
=> backend : re-implement set/reset session commands

quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/E2EContext.scala, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/controllers/DownloadControllerTest.scala
=> backend : add Listener.await(message) method

quix-frontend/service/package.json, quix-frontend/service/src/modules/auth/mock-strategy.ts, quix-frontend/service/src/modules/search/search.spec.ts, quix-frontend/service/src/modules/search/search.ts, quix-frontend/service/src/modules/search/types.ts, quix-frontend/service/src/modules/web-api/search.controller.ts, quix-frontend/service/test/app.e2e-spec.ts
@antonpod 
api is:
`/api/search/:term?offset=20&total=21`
returns:
```
{
notes: INote[],
count: number
}
```
=> add pagination in search

quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/PrestoQuixModule.scala, quix-backend/quix-modules/quix-presto-module/src/test/scala/quix/presto/PlainPrestoSqlSupportTest.scala
=> backend : filter out empty partial statements

quix-frontend/Dockerfile, quix-frontend/service/.testenv, quix-frontend/service/package.json, quix-frontend/service/src/app.controller.ts, quix-frontend/service/src/config/config.service.ts, quix-frontend/service/src/config/db-conf.ts, quix-frontend/service/src/config/db-connection.ts, quix-frontend/service/src/config/env.ts, quix-frontend/service/src/config/utils.ts, quix-frontend/service/src/main.ts, quix-frontend/service/src/modules/search/parser.ts, quix-frontend/service/src/modules/web-api/user-list.controller.ts, quix-frontend/service/src/utils/create-schema-helpers.ts, quix-frontend/service/test/app.e2e-spec.ts
- create schema only on one worker
- add typeorm verbose falg "DbDebug"
- make all phrases in search mandatory
- remove full text operators on search
=> [frontend-service] improvements

quix-frontend/service/src/modules/event-sourcing/plugins/notebook-plugin.ts, quix-frontend/service/src/modules/event-sourcing/quix-event-bus.spec.ts
=> add fav test

docker-compose.prebuilt.yml, docker-compose.yml, env-example
This was breaking "docker-compose up"
=> Change docker files to point to env-example not env_example

quix-backend/quix-webapps/quix-web-spring/src/main/scala/quix/web/spring/SpringConfig.scala
=> backend : do not fail whole application in case of missing jdbc driver

quix-backend/quix-webapps/quix-web-spring/src/main/scala/quix/web/controllers/DbController.scala, quix-backend/quix-webapps/quix-web-spring/src/test/scala/quix/web/controllers/PrestoDbControllerTest.scala
=> db : expose new endpoints to fetch schemas and tables

quix-backend/quix-core/src/main/scala/quix/core/sql/PrestoSqlOps.scala, quix-backend/quix-core/src/test/scala/quix/core/sql/PrestoSqlOpsTest.scala
handle leading whitespaces
should fix #58
=> handle trailing comments at the end of the scripts

quix-backend/quix-api/pom.xml, quix-backend/quix-modules/quix-jdbc-module/pom.xml, quix-backend/quix-modules/quix-presto-module/pom.xml
=> bump monix version to 3.0

quix-frontend/service/src/config/config.service.ts, quix-frontend/service/src/config/env/consts.ts, quix-frontend/service/src/config/env/env.ts, quix-frontend/service/src/main.ts
+  custom disk location for index.vm
=> frontend-service: allow rendering statics from cdn

quix-backend/quix-modules/quix-jdbc-module/src/main/scala/quix/jdbc/JdbcQueryExecutor.scala
=> fix npe in jdbc query executor

quix-frontend/Dockerfile, quix-frontend/shared/package.json
based on buster-slim, no dev npm packages
=> make frontend image smaller

documentation/website/pages/en/index.js
fix typo in website/pages/en/index.js
=> fix typo in web site

quix-backend/quix-core/src/main/scala/quix/core/history/dao/InMemoryHistoryDao.scala, quix-backend/quix-core/src/test/resources/db/001_init.sql, quix-backend/quix-core/src/test/scala/quix/core/history/dao/HistoryDaoContractTest.scala
fixes https://github.com/wix/quix/issues/261
=> [quix-backend] : make execution search case-insensitive

quix-backend/quix-webapps/quix-web-spring/pom.xml
should fix docker build of backend
=> fix : use correct maven dependency

quix-backend/quix-core/src/main/scala/quix/core/db/DbOps.scala, quix-backend/quix-core/src/test/scala/quix/core/db/DbOpsTest.scala, quix-backend/quix-core/src/test/scala/quix/core/db/DbQueryTest.scala
- return full catalog/schema tree in case of a match
- add ability to search for exact strings
=> feat(db-tree) : improve db tree search capabilities

quix-backend/quix-modules/quix-python-module/src/main/scala/quix/python/PythonExecutor.scala, quix-backend/quix-modules/quix-python-module/src/test/scala/quix/python/PythonExecutorTest.scala
it should expose the current user that executes the query
=> python-executor : add _get_user method

quix-frontend/lerna.json
https://github.com/wix-incubator/quix/actions/runs/5425460845/jobs/9866231767#step:10:8
=> Fix Lerna error

quix-frontend/client/package-lock.json, quix-frontend/service/package-lock.json, quix-frontend/service/package.json, quix-frontend/service/src/config/db-conf.ts, quix-frontend/service/src/entities/note/note.repository.ts, quix-frontend/shared/package-lock.json
Add missing and fix potentially failing code when using Mysql 8
update to mysql2
=> Frontend-Service: Support Mysql 8
